require('dotenv').config();
const path = require('path');

// TriBus covers 3 Florida agencies (Nature Coast into Tampa Bay), each
// with its own GTFS feed URL env var -- listing them here (rather than,
// say, a JSON array in one env var) keeps each one a normal single-value
// Render/`.env` secret, and keeps `GTFS_FEED_URL` (no suffix) working
// unchanged for any existing single-agency deployment, mapped to
// Hernando -- the agency this app originally shipped with alone.
const AGENCY_DEFS = [
  { id: 'hernando', label: 'Hernando County Transit', envVar: 'GTFS_FEED_URL_HERNANDO', legacyEnvVar: 'GTFS_FEED_URL' },
  { id: 'pasco', label: 'PascoGo', envVar: 'GTFS_FEED_URL_PASCO' },
  { id: 'hart', label: 'HART (Hillsborough Area Regional Transit)', envVar: 'GTFS_FEED_URL_HART' },
  // Citrus County Transit -- listed here inactive (no feed URL set
  // anywhere by default) because their real feed is currently NOT
  // fetchable by any automated client (Cloudflare-protected CMS blocks
  // it -- see .env.example for the full investigation). Once a
  // workaround exists, setting GTFS_FEED_URL_CITRUS activates it with no
  // code change needed here.
  { id: 'citrus', label: 'Citrus County Transit', envVar: 'GTFS_FEED_URL_CITRUS' },
];

// Only agencies with an actual configured feed URL are active -- lets a
// deployment run with just 1 or 2 agencies configured (e.g. while
// rolling out a new one) instead of all-or-nothing.
const agencies = AGENCY_DEFS
  .map(({ id, label, envVar, legacyEnvVar }) => ({
    id,
    label,
    feedUrl: process.env[envVar] || (legacyEnvVar && process.env[legacyEnvVar]) || null,
  }))
  .filter((a) => a.feedUrl);

module.exports = {
  agencies,
  refreshSecret: process.env.REFRESH_SECRET,
  etlCron: process.env.ETL_CRON || '0 3 * * *',
  port: process.env.PORT || 3000,

  // Optional: pre-seeds each stop's search aliases via Groq's free tier
  // (genuinely open-weight models -- Llama, not a closed model just
  // offered for free) at ETL time (see src/enrich.js). Entirely
  // optional -- leaving this unset just ships aliases: [] for every
  // stop, same as before this feature existed. Never required for the
  // app to work.
  groqApiKey: process.env.GROQ_API_KEY,
  // llama-3.1-8b-instant/llama-3.3-70b-versatile moved to Enterprise-only
  // ("Contact Sales") on Groq's current pricing page -- confirmed via
  // Groq's own Playground (which uses the account's session, not this
  // key) that openai/gpt-oss-20b (Apache-2.0 licensed, genuinely
  // open-weight) works on the plain $0 Free plan with no billing
  // required. Re-check https://console.groq.com/docs/models if this
  // ever 404s again -- Groq's free-tier model lineup has moved once
  // already.
  groqModel: process.env.GROQ_MODEL || 'openai/gpt-oss-20b',

  // Optional: renders a small static map image for a stop/landmark
  // answer via Geoapify's Static Maps API (OSM-based, free tier, no
  // credit card -- see src/staticmap.js for why this instead of
  // scraping OSM's own tile server). Leaving this unset just means
  // answers stay text-only, exactly as before this feature existed.
  geoapifyApiKey: process.env.GEOAPIFY_API_KEY,

  // Optional: when a rider's device is online, the rule-based query
  // engine's already-correct answer (see queryEngine.js -- this is
  // NEVER skipped or replaced, only rephrased) is optionally handed to
  // xAI's Grok for a more natural-language rewrite (src/grokAnswer.js).
  // A DIFFERENT provider from groqApiKey above (xAI's own "Grok" model
  // family via api.x.ai, not Groq's inference-hardware-hosted open
  // models) -- easy to confuse by name, kept as clearly separate config
  // entries. Leaving this unset just means every answer is the rule
  // engine's own text, unrephrased -- exactly this app's original
  // fully-offline behavior. See PRIVACY_POLICY.md: when this IS
  // configured, the query text and the rule engine's own factual answer
  // (never GPS coordinates) are sent to xAI for online riders only.
  xaiApiKey: process.env.XAI_API_KEY,
  xaiModel: process.env.XAI_MODEL || 'grok-4-fast',

  // On-disk locations. Everything here is regenerated by the ETL run and
  // is safe to delete -- nothing in backend/data is a source of truth,
  // the upstream GTFS feeds are. Each agency gets its own raw-extract
  // dir/zip path (data/raw/<agencyId>/, data/gtfs-<agencyId>.zip) so
  // e.g. Pasco's stops.txt can never overwrite Hernando's on disk before
  // either one is even parsed -- outputPath/aliasCachePath stay singular
  // since those hold the one final MERGED dataset/cache.
  dataDir: path.join(__dirname, '..', 'data'),
  rawDirFor: (agencyId) => path.join(__dirname, '..', 'data', 'raw', agencyId),
  zipPathFor: (agencyId) => path.join(__dirname, '..', 'data', `gtfs-${agencyId}.zip`),
  outputPath: path.join(__dirname, '..', 'data', 'transit_data.json'),
  aliasCachePath: path.join(__dirname, '..', 'data', 'alias-cache.json'),
};
