require('dotenv').config();
const path = require('path');

module.exports = {
  gtfsFeedUrl: process.env.GTFS_FEED_URL,
  refreshSecret: process.env.REFRESH_SECRET,
  etlCron: process.env.ETL_CRON || '0 3 * * *',
  port: process.env.PORT || 3000,

  // On-disk locations. Everything here is regenerated by the ETL run and
  // is safe to delete -- nothing in backend/data is a source of truth,
  // the upstream GTFS feed is.
  dataDir: path.join(__dirname, '..', 'data'),
  rawDir: path.join(__dirname, '..', 'data', 'raw'),
  zipPath: path.join(__dirname, '..', 'data', 'gtfs.zip'),
  outputPath: path.join(__dirname, '..', 'data', 'transit_data.json'),
};
